# 服务端口
server:
  port: 8207



# 服务名

spring:
  application:
    name: service-orders
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    password: 131421
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://192.168.11.11:27017/test

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #rabbitmq地址
  #spring.rabbitmq.host=192.168.44.165
  #spring.rabbitmq.port=5672
  #spring.rabbitmq.username=guest
  #spring.rabbitmq.password=guest
  # 配置rabbit
  rabbitmq:
    host: 192.168.11.11
    port: 5672
    username: guest
    password: guest

  redis:
    host: 192.168.11.11
    port: 6666