server:
  port: 8202


spring:
  application:
    name: service-cmn
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 131421

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  redis:
    host: 192.168.11.11
    port: 6666
    database: 0
    timeout: 1800000

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


