# 服务端口
server:
  port: 8201


# 服务名
spring:
  application:
    name: service-hosp
  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 131421

  #配置mongodb
  data:
    mongodb:
      uri: mongodb://192.168.11.11:27017/yygh


  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # 配置rabbit
  rabbitmq:
    host: 192.168.11.11
    port: 5672
    username: guest
    password: guest

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl