server:
  port: 8160

spring:
  application:
    name: service-user

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 131421
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    port: 6666
    host: 192.168.11.11

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 微信扫码登录接口
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    # 回调地址
    redirect_url: http://localhost:8160/api/user/wx/callback