#服务端口
server:
  port: 80


spring:
  application:
    #服务名称
    name: service-gateway
  cloud:

    gateway:
      discovery:
        locator:
          #使用服务发现路由
          enabled: true
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
              - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
              - Path=/*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates:
              - Path=/*/user/**
        - id: service-msm
          uri: lb://service-msm
          predicates:
              - Path=/*/msm/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
              - Path=/*/oss/**
        - id: service-orders
          uri: lb://service-orders
          predicates:
            - Path=/*/order/**
        - id: service-sta
          uri: lb://service-sta
          predicates:
            - Path=/*/statistics/**
    nacos:
      discovery:
        server-addr: localhost:8848



